### ISSUE TITLE
Add APICorpus

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1276]
Make a corpus class that allows harvesting data from an API and add it to Elasticsearch - if the API delivers JSON, this may even be possible without data wrangling.

**Comment by lukavdplas** [comment]
Since an API could also deliver XML, HTML or CSV data, and you could conceivably read JSON data from a directory, it makes sense to break this into two parts:

- an `APIFetcher` or whatever which fetches data from an API
- a `JSONCorpus` which is parallel to the `XMLCorpus`/`CSVCorpus`/ect, which handles any data wrangling.

You could structure a corpus definition as a combination of two mixin classes, something like:
- `APIFetcher` / `FileFetcher`
- `XMLReader` / `CSVReader` /  `JSONReader` / etc

Of course, this is assuming that we want API readers to be a part of the I-analyzer backend. We have discussed this before, but there are some reasons to say that it could make more sense to use a separate server to download source data from APIs.
